export enum ModuleTaskEnum {
    EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST",
    INVITE_USER = "INVITE_USER",
    RESET_PASSWORD = "RESET_PASSWORD",
    UPDATE_EMAIL = "UPDATE_EMAIL",
    UPDATE_PHONE_NUMBER = "UPDATE_PHONE_NUMBER",
    LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL",
    LOGIN_WITH_PHONE_NUMBER = "LOGIN_WITH_PHONE_NUMBER",
}
