import { CSSObjectWithLabel } from "react-select"
import { SweetAlertIcon } from "sweetalert2"

export const API_VERSION = "api/v1"

export const BASE_API_ENDPOINT = `${process.env.NEXT_PUBLIC_API_URL}/${API_VERSION}`
export const ALERT_ICON_TYPE = {
    // WARNING: "warning",
    warning: "warning",
    error: "error",
    info: "info",
    question: "question",
    success: "success",
} as Record<SweetAlertIcon, SweetAlertIcon>

export const MAX_INT_LIMIT = 2147483647
export const CONFIG = {
    REFRESH_TOKEN_MEMOIZED_TIME: 10000,
    LOG_IN_TITLE: "Login",
    MFA_VERIFY_TITLE: "MFA Verification",
    FORGOT_PASSWORD_TITLE: "Forgot Password",
    RESET_PASSWORD: "Setup New Password",
    SIGN_UP_TITLE: "Signup",
    FILE_UPLOAD_STATUS: {
        PENDING: "pending",
        COMPLETED: "completed",
    },
    FILE_TYPE: {
        IMAGE: {
            "image/png": [".png"],
            "image/jpeg": [".jpeg"],
            "image/jpg": [".jpg"],
        },
        VIDEO: {
            "video/mp4": [".mp4"],
            "video/mpeg": [".mpeg"],
            "video/quicktime": [".mov"],
            "video/webm": [".webm"],
        },
        PDF: {
            "application/pdf": [".pdf"],
        },
        CSV: {
            "text/csv": [".csv"],
        },
        XLSX: {
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
        },
        DOC: {
            "application/msword": [".doc"],
        },
        DOCX: {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
        },
        AUDIO: {
            "audio/mpeg": [".mp3"],
            "audio/wav": [".wav"],
        },
    },
    AUTH: {
        COOKIE_NAME: "__AT__",
    },
    WORD_SLICE_LIMIT: 50,
    WORD_SLICE_LIMIT_TWENTY: 20,
    IMAGE_SIZE: {
        CARD: "160x160",
        TABLE_LIST: "50x50",
        USER_CARD: "65x65",
        MEDIA_IMAGES: "300x300",
        MEDIA_LIBRARY_IMAGES: "60x80",
        MEDIA_LIBRAY_CARD_IMAGES: "500x500",
        LOGGED_IN_USER_HEADER_IMAGE: "30x30",
        MEDIA_LIBRARY_INFO_HEADER: "108x160",
        DISTRIBUTOR_REVENUE_IMAGE: "60x60",
        DISTRIBUTOR_AVATAR: "125x125",
        DEFAULT: "100x100",
        AIRLINE: "177x160",
        AIRLINE_NOTICE: "800x230",
        TIMELINE_IMAGE: "10x10",
    },
    ALL_OPTIONS: "__ALL__",
    LOCAL_STORAGE_VARIABLES: {
        USER__UUID: "user_uuid",
        COOKIE_CHOICE: "cookie_choice",
        ACCESS_TOKEN: "access_token",
        PERMISSIONS: "permissions",
        USER_DATA: "user_data",
        IS_AUTHENTICATED: "is_authenticated",
    },
    SESSION_STORAGE_VARIABLES: {
        PROFILE_IMAGE_URL: "profile_image_url",
    },
    DROPDOWN_LABEL_SLICE_LIMIT: 80,
    MESSAGES: {
        INVALID_LOGIN_CREDENTIALS: "Invalid email or password",
        ACCESS_TOKEN_EXPIRED: "Access token expired. Please login again",
        USER_EMAIL_VERIFIED: "Email verified successfully",
        USER_LOGIN_SUCCESS: "Great to see you!",
        OTP_RESENT_SUCCESS: "OTP sent successfully",
        OTP_RESENT_FAIL: "Unable to send OTP",
        INVALID_OTP: "Invalid OTP",
        GENERIC_ERROR: "Something went wrong",
        FORM_SUBMITTED_SUCCESS: "Form submitted successfully",
        PASSWORD_RESET_SUCCESS: "Password reset successfully. Please login",
        PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
        PASSWORS_SET_SUCCESS: "Password has been set successfully. Please login",
        UNABLE_TO_LOAD_DATA: "Unable to load data",
        USER_EMAIL_UPDATE_SUCCESS: "User email updated successfully. Please login again",
        THIS_CAN_NOT_BE_UNDONE: "This can not be undone.",
        DATA_ADDED_SUCCESSFULLY: "Data added successfully",
        DATA_DELETED_SUCCESSFULLY: "Data deleted successfully",
        WANT_TO_LOG_OUT: "Do you want to log out?",
        COPIED_SUCCESSFULLY: "Copied Successfully",
        FILE_UPLOAD_SUCCESSFULLY: "File uploaded successfully",
        DOWNLOAD_STARTED: "Download has been started, please check reports page for details.",
    },
    DEFAULT_MESSAGES: {
        TOKEN_EXPIRED: "Token expired. Please login again",
    },
    TOASTER_OPTIONS: {
        SUCCESS: {
            duration: 6000,
            style: {
                maxWidth: 450,
                borderRadius: "10px",
                background: "#14e4ea",
                color: "#fff",
            },
        },
        ERROR: {
            duration: 6000,
            style: {
                maxWidth: 450,
                borderRadius: "10px",
                background: "#CD0000",
                color: "#fff",
            },
        },
        HOLD: {
            duration: 6000,
            style: {
                maxWidth: 450,
                borderRadius: "10px",
                background: "#FFFF00",
                color: "#000",
            },
        },
    },
    DROPDOWN_STYLE: {
        control: (base: CSSObjectWithLabel) => ({ ...base, minHeight: "36px", maxHeight: "36px" }),
        menu: (base: CSSObjectWithLabel) => ({ ...base, zIndex: "9" }),
        valueContainer: (base: CSSObjectWithLabel) => ({
            ...base,
            overflow: "auto",
            maxHeight: "33px",
        }),
        singleValue: (base: CSSObjectWithLabel) => ({
            ...base,
            height: "18px",
            color: "#5e6278",
            fontWeight: 500,
            fontSize: "14px",
        }),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        option: (base: CSSObjectWithLabel, state: any) => ({
            ...base,
            color:
                state.isDisabled && state.isSelected
                    ? "#fff"
                    : state.isDisabled
                      ? "#808080"
                      : state.isSelected
                        ? "#fff"
                        : "#242565",
            ":hover": { backgroundColor: state.isSelected ? "#242565" : "#DEEBFF" },
            backgroundColor: state.isSelected ? "#242565" : "none",
        }),
        dropdownIndicator: (base: CSSObjectWithLabel) => ({ ...base, padding: "6px" }),
        clearIndicator: (base: CSSObjectWithLabel) => ({ ...base, padding: "6px" }),
    },
    COGNITO_CHALLENGE_NAME: {
        CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE: "CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE",
        CONTINUE_SIGN_IN_WITH_MFA_SELECTION: "CONTINUE_SIGN_IN_WITH_MFA_SELECTION",
        CONFIRM_SIGN_IN_WITH_SMS_CODE: "CONFIRM_SIGN_IN_WITH_SMS_CODE",
        CONFIRM_SIGN_IN_WITH_TOTP_CODE: "CONFIRM_SIGN_IN_WITH_TOTP_CODE",
        CONTINUE_SIGN_IN_WITH_TOTP_SETUP: "CONTINUE_SIGN_IN_WITH_TOTP_SETUP",
        CONFIRM_SIGN_UP: "CONFIRM_SIGN_UP",
        RESET_PASSWORD: "RESET_PASSWORD",
        DONE: "DONE",
        CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED: "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED",
    },
    COGNITO_AUTH_PROVIDERS: {
        // this type assertion is required for login provider to work with typescript
        GOOGLE: "Google" as const,
    },
    COGNITO_AUTH_EXCEPTIONS: {
        // this type assertion is required for login provider to work with typescript
        USER_NOT_CONFIRMED: "UserNotConfirmedException",
    },
    PARAMS: {
        REDIRECT_URL_PARAM: "next",
        EDIT_PARAM: "edit",
    },
    CLIENT_UPLOAD_VIA_FILE: {
        TYPES: [
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-excel",
            "application/msexcel",
            "application/x-msexcel",
            "application/x-ms-excel",
            "application/x-excel",
            "application/x-dos_ms_excel",
            "application/xls",
            "application/x-xls",
        ],
    },
    URL: {
        LOCALHOST: "http://localhost:3000",
    },
    STATUS: {
        UNAUTHORIZED: 401,
        NO_CONTENT: 204,
        NOT_FOUND: 404,
        SERVER_ERROR: 500,
    },
    DEBOUNCE_TIMEOUT: 500,
    PAGINATION: {
        TYPE: "pagination",
        SIZE: 15,
        PAGE: 1,
    },
    PAGE_SIZE_OPTIONS: { 15: 15, 25: 25, 50: 50, 100: 100 },
    SKELETON_CONFIGURATION: {
        SKELETON_ROWS_COUNT: 5,
        SKELETON_HEIGHT: 60,
    },
    VALIDATIONS: {
        CHARACTER_LENGTH: {
            CHARS_255: 255,
            CHARS_1: 1,
            CHARS_3: 3,
            CHARS_4: 4,
            CHARS_5: 5,
            CHARS_6: 6,
            CHARS_60: 60,
            CHARS_20: 20,
        },
        MESSAGE: {
            ALPHANUMERIC: "Only alphanumeric characters are allowed",
            NUMERICAL_VALUES_REQUIRED: "Only numeric value is allowed",
            MAX_CHARACTERS: "must be in range of 0 and 2147483647",
            EMAIL_REQUIRED: "Email address is required",
            SIGNATURE_REQUIRED: "Signature is required",
            DOCUMENT_REQUIRED: "Document is required",
            GST_CERTIFICATE_REQUIRED: "GST certificate is required",
            FILE_REQUIRED: "File is required",
            INVALID_URL: "Invalid URL",
            USER_PASSWORD:
                "Must contain a combination of letters, numbers and special character with one uppercase and lowercase character",
            POSITIVE_NUMERICAL_VALUES_REQUIRED: "Only positive numeric value is allowed",
            VALIDATION_FAILED: "Unable to proceed. \n Please fill in all mandatory fields (*)",
            MAX_INT_LIMIT: `${MAX_INT_LIMIT} is the maximum limit`,
            INVALID_PHONE_NUMBER: "Invalid phone number",
            PASSWORD_DO_NOT_MATCH: "Password do not match",
            ONLY_JPG_PNG_JPEG_ALLOWED: "only jpg, png and jpeg files are accepted",
            ONLY_XLSX_FILE_ACCEPTED: "Only .xlsx file is accepted",
        },
        FIELD_NAME: {
            NAME: "Name",
            EMAIL: "Email",
            GSTN: "GSTN",
            GST: "GST",
            PASSWORD: "Password",
            CONFIRM_PASSWORD: "Confirm password",
            CURRENT_PASSWORD: "Current password",
            NEW_PASSWORD: "New password",
            FIRST_NAME: "First name",
            LAST_NAME: "Last name",
            ADDRESS_TYPE: "Address type",
            ADDRESS: "Address",
            PINCODE: "Pincode",
            city: "City",
            state: "State",
            country: "Country",
            COUNTRY_CODE: "Country code",
            OTP: "OTP",
            PERMISSION: "Permission",
            ROLE: "Role",
        },
    },
    USER_ACCESS: [
        { label: "Admin", value: "Admin" },
        { label: "Finance", value: "Finance" },
        { label: "Sales", value: "Sales" },
        { label: "Marketing", value: "Marketing" },
    ],

    LOADER_TYPES: {
        TABLE_SKELETON: "table-skeleton",
        CARD_SKELETON: "card-skeleton",
    },
    DEFAULT_TABLE_SKELETON_ROW_COUNT: 4,
    CARD_SKELETON_BASIS: 95,
    STATUS_CODES: {
        SUCCESS: 200,
        NO_CONTENT: 204,
        UNAUTHORIZED: 401,
        SERVER_ERROR: 500,
        FORBIDDEN: 403,
    },
    API_ENDPOINTS: {
        GET_USER_BY_TOKEN: new URL(`${BASE_API_ENDPOINT}/user/get-user-by-token`),
        CONFIRM_VERIFICATION_CODE: new URL(`${BASE_API_ENDPOINT}/user/confirm-verification-code`),
        RESEND_VERIFICATION_CODE: new URL(`${BASE_API_ENDPOINT}/user/resend-verification-code`),
        CREATE_USER: new URL(`${BASE_API_ENDPOINT}/user/create`),
        VERIFY_GOOGLE_USER: new URL(`${BASE_API_ENDPOINT}/user/idp-callback`),
        LOGIN: new URL(`${BASE_API_ENDPOINT}/auth/login `),
        FORGOT_PASSWORD: new URL(`${BASE_API_ENDPOINT}/auth/forgot-password`),
        RESET_PASSWORD: new URL(`${BASE_API_ENDPOINT}/auth/reset-password`),
        GOOGLE_LOGIN: new URL(`${BASE_API_ENDPOINT}/auth/google/login`),
        BASE_USER: new URL(`${BASE_API_ENDPOINT}/user`),
        GET_USER_DETAILS: new URL(`${BASE_API_ENDPOINT}/user/details`),
        SIGNUP: new URL(`${BASE_API_ENDPOINT}/auth/signup `),
        BASE_OTP_SEND: new URL(`${BASE_API_ENDPOINT}/otp/send`),
        LOGOUT: new URL(`${BASE_API_ENDPOINT}/auth/logout `),
        REFRESH_TOKEN: new URL(`${BASE_API_ENDPOINT}/auth/refresh`),
        GET_ROLE_DETAIL: new URL(`${BASE_API_ENDPOINT}/role`),
        CREATE_ROLE: new URL(`${BASE_API_ENDPOINT}/role/create`),
        EDIT_ROLE: new URL(`${BASE_API_ENDPOINT}/role`),
        GET_ROLES: new URL(`${BASE_API_ENDPOINT}/role/list`),
        GET_USERS: new URL(`${BASE_API_ENDPOINT}/user/list`),
        INVITE_USER: new URL(`${BASE_API_ENDPOINT}/user/invite`),
        GET_COLUMN_METADATA: new URL(`${BASE_API_ENDPOINT}/common/column-metadata`),
        UPDATE_USER_DETAILS: new URL(`${BASE_API_ENDPOINT}/user/update`),
        UPDATE_PASSWORD: new URL(`${BASE_API_ENDPOINT}/user/update/password`),
        BASE_OTP_VERIFY: new URL(`${BASE_API_ENDPOINT}/otp/verify`),
        GET_S3_UPLOAD_URL: new URL(`${BASE_API_ENDPOINT}/document/upload/url`),
        GET_S3_DOWNLOAD_URL: new URL(`${BASE_API_ENDPOINT}/document/download/url`),
        DOWNLOAD_BULK_UPLOAD_SAMPLE_FILE: new URL(`${BASE_API_ENDPOINT}/bulk-upload/sample`),
        BULK_UPLOAD: new URL(`${BASE_API_ENDPOINT}/bulk-upload`),
        BULK_DOWNLOAD: new URL(`${BASE_API_ENDPOINT}/bulk-download`),
        GET_QUEUE_TASKS: new URL(`${BASE_API_ENDPOINT}/queue-task/list`),
        GET_QR_CODE: new URL(`${BASE_API_ENDPOINT}/auth/mfa/qr-code`),
        VERIFY_MFA: new URL(`${BASE_API_ENDPOINT}/auth/mfa/verify`),
        UPDATE_MFA_STATUS: new URL(`${BASE_API_ENDPOINT}/auth/mfa/status`),
    },
    OTP_AND_VERIFY_ENDPOINTS: {
        LOGIN: "login",
        EMAIL_UPDATE: "email-update",
        PHONE_NUMBER_UPDATE: "phone-number-update",
    },
    COLOR_ARRAY: {
        colorArray: [
            "#FF6633",
            "#FFB399",
            "#00B3E6",
            "#E6B333",
            "#3366E6",
            "#999966",
            "#99FF99",
            "#B34D4D",
            "#80B300",
            "#809900",
            "#E6B3B3",
            "#6680B3",
            "#66991A",
            "#FF99E6",
            "#CCFF1A",
            "#FF1A66",
            "#E6331A",
            "#33FFCC",
            "#66994D",
            "#B366CC",
            "#4D8000",
            "#B33300",
            "#CC80CC",
            "#66664D",
            "#991AFF",
            "#E666FF",
            "#4DB3FF",
            "#1AB399",
            "#E666B3",
            "#33991A",
            "#CC9999",
            "#B3B31A",
            "#00E680",
            "#4D8066",
            "#809980",
            "#E6FF80",
            "#1AFF33",
            "#999933",
            "#FF3380",
            "#CCCC00",
            "#66E64D",
            "#4D80CC",
            "#9900B3",
            "#E64D66",
            "#4DB380",
            "#FF4D4D",
            "#99E6E6",
            "#6666FF",
        ],
    },
    SWEETALERT_DELETE_OPTION: {
        text: "Are you sure you want to delete",
        icon: ALERT_ICON_TYPE.warning,
        showCancelButton: true,
        confirmButtonColor: "#d33",
        cancelButtonColor: "#3085d6",
        confirmButtonText: "Yes, Delete",
        confirmButtonTextSecondary: "Yes",
        cancelButtonText: "Cancel",
    },
    SWEETALERT_SUCCESS_OPTION: {
        icon: ALERT_ICON_TYPE.success,
        showConfirmButton: false,
        timer: 5000,
    },
    ADD_ROLE_ITEM_STEP_TABS: {
        details: {
            label: "Details",
            path: "details",
        },
    },
    EDIT_USER_STEP_TABS: {
        details: {
            label: "Details",
            path: "details",
        },
    },
    REACT_TABLE: {
        COLUMN_SIZE: {
            100: 100,
        },
    },
    ADDRESS_DEFAULT_VALUE: {
        address: "",
        address_type: null,
        city: null,
        country: null,
        pincode: null,
        state: null,
    },
    CODE: {
        INVALID_FILE_TYPE: "file-invalid-type",
        FILE_TOO_LARGE: "file-too-large",
    },
}
// Endpoints that do not require authentication
export const OPEN_ENDPOINTS: string[] = [
    CONFIG.API_ENDPOINTS.LOGIN.href,
    CONFIG.API_ENDPOINTS.FORGOT_PASSWORD.href,
    CONFIG.API_ENDPOINTS.RESET_PASSWORD.href,
    CONFIG.API_ENDPOINTS.GOOGLE_LOGIN.href,
    CONFIG.API_ENDPOINTS.SIGNUP.href,
]
export const CHAR_DEFAULT_MAX_LENGTH = CONFIG.VALIDATIONS.CHARACTER_LENGTH.CHARS_60
